name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Gradle version
      # Gradle 8.10!
      run: gradle --version
    - name: GradleW version
      run: echo fails ./gradlew --version

    - name: Build with Gradle
      #run: ./gradlew build
      # based on https://stackoverflow.com/a/54359875
      run: gradle build
  
